const express=require("express")
const router=express.Router()
const cartController=require("../controllers/cartController")
const verifyJWT=require("../middleware/verifyJWT")
router.use(verifyJWT)
router.get("/get-cart",cartController.getCart)
router.post("/add",cartController.addProduct)
router.get("/:id",cartController.getProductById)
router.delete("/delete/:productId",cartController.deleteProduct)
module.exports=router